### ISSUE TITLE
Update a Row (Picker) with New Values After loadForm()

### ISSUE THREAD

**Issue by jsonmat** [ortuman/SwiftForms#102]
I need to update the values in a row(pickers) after loadForm() function. How do I do it? Is there any reference I can use for that row?

**Comment by jsonmat** [comment]
Can you please reply?

**Comment by ortuman** [comment]
Updating rowValue property of the row descriptor and reloading the table should work.

**Comment by jsonmat** [comment]
Thank you so much! Which function will I use to reload the table?

**Comment by jsonmat** [comment]
My biggest problem here is where to put the code of setting new values for my row (picker). I tried putting it inside FormPickerCell > didSelectRow but I couldn't do it.

**Comment by jsonmat** [comment]
Please help me..

**Comment by ortuman** [comment]
try calling self.tableView.reloadData() from your "FormViewController"
