### ISSUE TITLE
unable to update the values of form cells

### ISSUE THREAD

**Issue by padotj** [ortuman/SwiftForms#11]
I have a scenario where a user may select auto-fill a form by copying a record.  I can successfully retrieve the record, but I'm not sure how to go about setting the form row values and having those values reflected in the UI.  

The approach I am using presently is to iterate over the rows in each section and setting row.value to my value.

Any tips would be greatly appreciated.  

Sincerely,
@padotj

**Comment by AnnieNinaJoyceV** [comment]
Hi thank you very much for your library. I am working on auto-fill for our project. I am stuck at getting the filled value.
Say I have an email field along with 5 other fields. Once user entered a value in email field, I will verify if there is an existing record in server, if so I fill show the respective values in remaining 5 fields.
I am struggling to figure out how would I know whether user entered a value or not in email field?

Thanks.
