### ISSUE TITLE
Cannot enter more than one character in a password field

### ISSUE THREAD

**Issue by vrwim** [ortuman/SwiftForms#12]
Rows with .Password as RowType cannot handle more than one character. I have tested this on an iPhone 5, iPad retina and the simulator. I have not found a way to fix/circumvent this bug.

Tested on Xcode 6.1.1 and Yosemite 10.10.1; using SDK 8.1 on iOS 8.1.2

**Comment by tosbaha** [comment]
Thanks.

**Comment by ortuman** [comment]
The current version fixes this issue. Thanks for the report.

**Comment by mknippen** [comment]
This issue still exists in the demo app. Downloading the source code and running without any changes shows this same error.
