### ISSUE TITLE
Xcode: The operation couldn't be completed.

### ISSUE THREAD

**Issue by tomtom1992** [ortuman/SwiftForms#120]
LaunchServicesError error 0

When trying to run the sample application in iOS Simulator

**Comment by iLandes** [comment]
Hello tomtom, I have the problem with the demo project downloading from github.

I found the answer on stackoverflow.com :  [here](http://stackoverflow.com/questions/25130558/unable-to-run-app-in-simulator-an-error-was-encountered-while-running-domain)

On SwiftFormApplication Taget I change the identifier to : com.ortulabs.SwiftFormsApplication

Then I select in menu "Product" : "Clean" item.

It's works for me… I hope it's help you
