### ISSUE TITLE
Can't see No parameter constructor in "FormDescriptor.swift"

### ISSUE THREAD

**Issue by SatyaAchanta** [ortuman/SwiftForms#125]
I am trying to use FormViewController with the help of read me file you included in this page, but when I try to implement that, I have to send "title" as parameter in FormDescriptor. Is there any inconsistency between the readme file and actual implementation or Did I go somewhere wrong in installation ?, FYI, I am unable to find No parameter constructor in "FormDescriptor.swift" class.

**Comment by ortuman** [comment]
Fixed in 1.5
