### ISSUE TITLE
Date type didn't set in cell

### ISSUE THREAD

**Issue by pluckq** [ortuman/SwiftForms#127]
![simulator screen shot 30 2016 20 09 24](https://cloud.githubusercontent.com/assets/5019512/17271322/e900361c-5699-11e6-98e2-75cef9edb2ac.png)

**Comment by pluckq** [comment]
Fixed it by using my own date formatter in DateCell class

**Comment by ortuman** [comment]
Definitely a bug. Fixed on 1.6.1. Thx!
