### ISSUE TITLE
pod update failing

### ISSUE THREAD

**Issue by vineethvijayan** [ortuman/SwiftForms#129]
Dear Team, 

I was using 1.0.2 version of SwiftForms and when I updated the pod, it is giving me a lot of errors

![screen shot 2016-08-03 at 5 35 00 pm](https://cloud.githubusercontent.com/assets/6049347/17364929/c5127238-59a0-11e6-809d-278bb8a5b457.png)

Please help, should I update or roll back to 1.0.2?

Thanks a lot.

**Comment by ortuman** [comment]
Yo should use new API, or either downgrade to any version prior to 1.5
