### ISSUE TITLE
Override valueChanged(_:UISlider) method

### ISSUE THREAD

**Issue by peterkasa** [ortuman/SwiftForms#132]
I cannot override valueChanged method in a subclass of FormSliderCell. Can be changed the access control of the valueChanged(_:UISlider) to public in FormSliderCell.swift?
Thanks!

**Comment by ortuman** [comment]
You can override "update" method, which will be invoked everytime the slider value changes.

**Comment by appsird** [comment]
The README describes custom cells, though an example may help someone. 


`// use this extension in mySlidercell  to display slider value
extension Double {
    func format(_ f: String) -> String {
        return String(format: "%\(f)f", self)
    }
}
`
Create a custom slider class:

`class mySlidercell: FormSliderCell {
    
    override func update() {
        super.update()
        if let value = rowDescriptor?.value as? Float {
            let v = Double(value)
            self.titleLabel.text = v.format(".0")
        }
    }
}
`

`// 

 var radius: Int!   

fileprivate func loadForm() {
        let section2 = FormSectionDescriptor(headerTitle: "Search Radius", footerTitle: nil)
        row = FormRowDescriptor(tag: Static.radius, type: .slider, title: "")
        
        let aClass: AnyClass = mySlidercell.self
        row.configuration.cell.cellClass = aClass
        
        row.configuration.stepper.maximumValue = 1000.0
        row.configuration.stepper.minimumValue = 1.0
        row.configuration.stepper.steps = 1.0
        row.configuration.stepper.continuous = true
        row.value = Float(self.radius) as AnyObject
        section2.rows.append(row)
}
`
