### ISSUE TITLE
Password field

### ISSUE THREAD

**Issue by david2Coders** [ortuman/SwiftForms#133]
Each time a char is press over a password field the textfield is cleared.

This is the action
`textField.addTarget(self, action: #selector(FormTextFieldCell.editingChanged(_:)), forControlEvents: .EditingChanged)`

and I solved removing the recursive update() call
`internal func editingChanged(sender: UITextField) {
        print(sender.text)
        guard let text = sender.text where text.characters.count > 0 else { rowDescriptor?.value = nil; update(); return }
        rowDescriptor?.value = text
        //  update() <--- REMOVED
    }`

**Comment by ortuman** [comment]
Issue fixed on 1.6.3. Thx!
