### ISSUE TITLE
iOS 10 support

### ISSUE THREAD

**Issue by appsird** [ortuman/SwiftForms#134]
Does a beta version exist for iOS 10?

**Comment by ortuman** [comment]
There are two additional branches "Swift2.3" and "Swift3" that you can use.

**Comment by appsird** [comment]
thanks!

**Comment by appsird** [comment]
for the benefit of others...

You bring in the iOS 10 Swift 3 compatible branch by placing the following in your Podfile

pod 'SwiftForms', :git => 'https://github.com/ortuman/SwiftForms.git', :branch => 'Swift3'
