### ISSUE TITLE
How to set UITableViewCellSelectionStyle to none?

### ISSUE THREAD

**Issue by andytriboletti** [ortuman/SwiftForms#136]
I have some labels where I don't want the user to be able to tap on the row and get a highlight.

What I've tried:
```
let row = FormRowDescriptor(tag: "no_image", type: .label, title: "No Image Attached")
row.configuration.cell.appearance = [ "selectionStyle" : UITableViewCellSelectionStyle.none as AnyObject ]
```

The app crashes when I try to set the selectionStyle.

I can disable selection on the whole table by calling `self.tableView.allowsSelection = false` but I want buttons in the form to be able to be clicked.

**Comment by ortuman** [comment]
Try setting row configuration value as follows:

row.configuration.cell.appearance = [ "selectionStyle" : UITableViewCellSelectionStyle.none.rawValue]
