### ISSUE TITLE
increase rows in multiline text

### ISSUE THREAD

**Issue by appsird** [ortuman/SwiftForms#137]
is it possible to increase the text area rows for .multilineText?

**Comment by donaldhughes** [comment]
I came here to ask the same question.

**Comment by ortuman** [comment]
@donaldhughes that's right. 

To use your custom class:

let descriptor = ...

descriptor.configuration.cell.cellClass = TallFormTextViewCell.self

**Comment by donaldhughes** [comment]
Thanks!  It was the `.self` that I wasn't doing.
