### ISSUE TITLE
Use Legacy Swift Language Version

### ISSUE THREAD

**Issue by jorgeefrazaocosta** [ortuman/SwiftForms#139]
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

**Comment by jorgeefrazaocosta** [comment]
I also have forced to get the 1.7 version using cocoapods and I get the following error message:

[!] Unable to satisfy the following requirements:

- `SwiftForms (= 1.7)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `SwiftForms (= 1.7)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by hslightnin** [comment]
`post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end`

That end the end of the pod file fixed the error for multiple pods

**Comment by ortuman** [comment]
I recently add Swift3 pod compatibility. Should work now. Thank you!
