### ISSUE TITLE
MultilineText getting null

### ISSUE THREAD

**Issue by aldolinares** [ortuman/SwiftForms#16]
Hi I have a form with 3 objects, .Email .MultipleSelector .MultilineText and a .Button. 

If I only fill the MultiLineText I get Null on it, but If I fill any other I get the value from the MultiLineText

**Comment by spritesun** [comment]
@tosbaha Thanks.
This should be merge into the master.

**Comment by ortuman** [comment]
Fixed in the last commit. Thanks for reporting this issue guys. ;)
