### ISSUE TITLE
Swift4 version crash

### ISSUE THREAD

**Issue by appsird** [ortuman/SwiftForms#160]
I compiled and ran your example, and all appeared to work.

Though, I continued to crash when running my loadform(), receiving exceptions. On closer inspection,  I click on your project file in Xcode 9 beta3, and notice the Swift Language version was set to "unspecified". Though, I click each SwiftFormsApplication and SwiftForms targets and note these were set to use Swift4.

With the above setting, I then compile and see compile warnings and runtime errors. See images below. Note the error on line 136 of FormViewController.swift.

THis is the exact same place where I experience a crash when running in my application. Specifically if I set a cell.appearance, like:

        let row2 = FormRowDescriptor(tag: Static.subtitleTag, type: .text, title: "Subtitle")
        row2.configuration.cell.appearance = ["textField.placeholder" : "Classification" as AnyObject,
                                             "textField.textAlignment" : NSTextAlignment.right.rawValue as AnyObject]

Then, I will receive a crash on the line 136.

Appears there is something new in Swift4 regarding key/value changes which was not present in Swift 3. 

Would appreciate any assistance. I can send you my modified project if you would like to take a look.

![pic1](https://user-images.githubusercontent.com/8471833/28047856-f57d4f66-65a1-11e7-90bd-f8d28e8a42c2.png)
![pic2](https://user-images.githubusercontent.com/8471833/28047858-f7005c7a-65a1-11e7-838d-6b0cc5e6ed7a.png)

**Comment by appsird** [comment]
Here is a pic of the setting changed from unspecified to swift4

![pic3](https://user-images.githubusercontent.com/8471833/28047989-d7531448-65a2-11e7-8b22-a89a7d56cdc0.png)

**Comment by morgan-legal** [comment]
Hello, I'm still having the issue after changing the swift language version to swift 4.0. Any ideas ?

**Comment by appsird** [comment]
The current Swift4 branch here has runtime problems as described above.

pod 'SwiftForms', :git => 'https://github.com/ortuman/SwiftForms.git', :branch => 'Swift4'

I'm currently running the standard Swift3 branch:

pod 'SwiftForms'

make certain to specify swift language version appropriately like described above.

I would still appreciate a fully functioning Swift4 version which does not experience runtime errors, which appear are related to new Key/Value handling in Swift4/Xcode9.

**Comment by trusk89** [comment]
Can confirm. Broken on swift 4.

**Comment by ortuman** [comment]
Current master version has been adapted to Swift4. Sorry for the issues.

**Comment by appsird** [comment]
Thanks Miguel.

**Comment by trusk89** [comment]
Nope. Just updated in my project and the issue still reproduces.

**Comment by appsird** [comment]
I only now updated to the latest Swift4 release using the following in my Podfile:

I'm running Xcode Version 9.0 (9A235)

pod 'SwiftForms', :git => 'https://github.com/ortuman/SwiftForms.git', :branch => 'Swift4'

Upon running 'pod install' I received the status:

Using SwiftForms (1.7)

Running my application with this version yields an error on the same line. Prior the error was in purple, i.e. runtime error. Now the errors green.

![untitled](https://user-images.githubusercontent.com/8471833/31643716-022b4612-b2a7-11e7-9b63-7092601238cb.png)

**Comment by trusk89** [comment]
I'm using 1.7 from master not a specific branch and it's still fine. 1.8, the latest from master still crashes for me.

**Comment by appsird** [comment]
Miguel,

Appears your Swift4 branch is deprecated and changes are folded into the master branch. To avoid confusion, can the Swift4 branch be removed.

trusk89,
I installed master branch 1.8.1 and ran without seeing any errors. Here's my setup;

iPhone5, iPhone7
Xcode 9.0.1
SwiftForms Pod Build Settings 'Swift Language Version' set to Swift 4
Podfile line:
  pod 'SwiftForms'

I'm not seeing any issues currently. Please match the above and see if you continue to have errors. I typically delete the Pods project and ancillary Pod folder in the project, quit out of Xcode, then 'pod update', then 'pod install. Then relaunch Xcode.

**Comment by trusk89** [comment]
@appsird nope, still crashes for me
```Installing SwiftForms 1.8.1 (was 1.7)```

    Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<SwiftForms.FormPickerCell 0x150063200> valueForUndefinedKey:]: this class is not key value coding-compliant for the key valueLabel.'
    *** First throw call stack:
    (0x186473d38 0x185988528 0x186473a00 0x186e1b864 0x186d61f70 0x186d92814  0x101721188 0x101721398 0x18fbb8474 0x18fbb89d8 0x18fb98670 0x18f953f10 0x18f880000 0x18a4510b4 0x18a455194 0x18a3c3f24 0x18a3ea340 0x18a3eb180 0x18641b8b8 0x186419270     0x18641982c 0x18633a2d8 0x1881cbf84 0x18f8e6880 0x1004130d8 0x185e5e56c)
    libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by trusk89** [comment]
Thanks for the feedback @appsird! I'll spend some time debugging this weekend.

**Comment by gisngocthach** [comment]
@trusk89 Have you found the reason? I did have the same problem BUT not with the SwiftForm example.

**Comment by trusk89** [comment]
@appsird @gisngocthach I have time today. I've forked it and will look into fixing it and open a PR.

**Comment by abanet** [comment]
I just get same error (FormViewController - line 136)  after update SwiftForms to 1.8.2 version. I'm working with Xcode 10 and swift 4.2.
