### ISSUE TITLE
[booleanSwitch] default value

### ISSUE THREAD

**Issue by rjong** [ortuman/SwiftForms#167]
Hi there,

How can I set the booleanSwitch 'on' by default? I proceed already:
`row1.value = true as AnyObject`
`row1.value = "true" as AnyObject`
`row1.value = "1" as AnyObject`

Thanks!

**Comment by rjong** [comment]
Anyone?

**Comment by erolando** [comment]
row.value = (employee.isActive ?? false) as AnyObject

works for me
