### ISSUE TITLE
new Xcode 9.2 warnings

### ISSUE THREAD

**Issue by appsird** [ortuman/SwiftForms#168]
When recompiling my project under the latest Xcode 9.2 beta (9C34B) I receive numerous warnings from code within SwiftForms of the attached form.

  'characters' is deprecated: Please us String or Substring directly

![untitled](https://user-images.githubusercontent.com/8471833/33184311-c1e2b692-d030-11e7-9784-d053c81f015d.png)

My understanding this release will go production soon.

Would appreciate an update which removes the warnings.

Thanks again so much for a great form framework, I really appreciate your efforts.

**Comment by appsird** [comment]
fyi: I believe these should now be coded as follows:

text.characters.count.  <-old
text.count.  <- new Xcode 9.2 beta

**Comment by ortuman** [comment]
Issue fixed on commit ef3102c.

**Comment by appsird** [comment]
Thanks so much!
