### ISSUE TITLE
How can I make the picker disappear?

### ISSUE THREAD

**Issue by Kinzi** [ortuman/SwiftForms#21]
How can I make the picker disappear when tapping elswhere on the screen? (i.e. outside any other formcells)

usually something like:

    `override func touchesBegan(touches: NSSet, withEvent event: UIEvent) {
        
                self.view.endEditing(true)
        
            }`
works, but I don't know where to put it to get it work...
Any ideas?

btw: this is a great piece of coding! Thanks for sharing!

THX!
Kinzi

**Comment by ortuman** [comment]
Try using that very same piece of code in the FormViewController class.

**Comment by Kinzi** [comment]
Hey! thanks for the quick reply! unfortunately no: if i just put it into FormViewController its not getting executed at all... any other idea?

**Comment by ortuman** [comment]
Mmmmm, you may try to add an overlay view of the same frame to the 'tableView' form property. Attach to it a tap gesture recognizer, and when triggered call "endEditing". Hope it helps.
