### ISSUE TITLE
dynamic row addition?

### ISSUE THREAD

**Issue by swangy** [ortuman/SwiftForms#26]
Hi is there a simple way of adding form rows dynamically based on something picked in previous row?

**Comment by ortuman** [comment]
As easy as changing form descriptors and reloading table data.

e.g.

// Adding a new row to the last section…

let sections = self.form.sections

sections[sections.endIndex - 1].append(FormRowDescriptor(…))

tableView.reloadData()

Hope it helps! ;)

Regards.

**Comment by swangy** [comment]
cool thanks!

**Comment by vineethvijayan** [comment]
@swangy is it possible to reload data in a picker view using this logic. 

I have tried my best but all in vain :(

stateIDs = ["ABC", "DEF"]
form.sections[2].rows[4] = FormRowDescriptor(tag: "state", rowType: FormRowType.Picker, title: "StateABC")
form.sections[2].rows[4].configuration[FormRowDescriptor.Configuration.Options] = stateIDs
tableView.reloadData()

**Comment by swangy** [comment]
i got some code working, let me dig it up..!

**Comment by vineethvijayan** [comment]
Thanks @swangy What I am trying to do is have 2 picker view, like country and state. I need to reload states when ever country is changed. I am trying my best to get it working :(
