### ISSUE TITLE
How to set picker value?

### ISSUE THREAD

**Issue by mgerlach-klick** [ortuman/SwiftForms#28]
Hey, could you please tell me if there is a way to set a picker value to one of its options? If the picker itself were exposed I could use something like 'picker.selectRow', but I don't see it? Thank you!

**Comment by ortuman** [comment]
Hi!

Just set the row descriptor ‘value’ property to one of the available options.

Here’s a code snippet taken from the repository example project:

row = FormRowDescriptor(tag: Static.picker, rowType: .Picker, title: "Gender")
row.configuration[FormRowDescriptor.Configuration.Options] = ["F", "M", "U"]
row.value = "M"

Remember to set title formatter in order to display values properly…

row.configuration[FormRowDescriptor.Configuration.TitleFormatterClosure] = { value in
            switch( value ) {

            case "F":
                return "Female"

            case "M":
                return "Male"

            case "U":
                return "I'd rather not to say"

            default:
                return nil
            }
} as TitleFormatterClosure

Hope it helps! ;)

**Comment by mgerlach-klick** [comment]
Thank you Miguel, I appreciate your swift (*haw haw* :smiley: ) answer! Sadly, this doesn't work for me:

```
        let snapshotModeSection = FormSectionDescriptor()
        let snapshotMode = FormRowDescriptor(tag: "picker", rowType: .Picker, title: "Snapshot Mode")
        snapshotMode.configuration[FormRowDescriptor.Configuration.Options] = ["full", "partial"] 
        snapshotMode.configuration[FormRowDescriptor.Configuration.TitleFormatterClosure] = { value in
            switch( value ) {
            case "full":
                return "Full Screen"
                
            case "partial":
                return "Visible Portion"
     
            default: 
                return nil 
            } 
            } as TitleFormatterClosure
        
		snapshotMode.value = "partial" 
```
This always shows "Full Screen" as the selected value in the picker(!) - the actual selected option that I see in the tableview is correct. Any ideas?

**Comment by mgerlach-klick** [comment]
Okay, so basically in the FormPickerCell class, in the update() function, in the "if rowDescripor.value != nil {..." block we'd need to add picker.selectRow($indexOfValue, inComponent: $isThereEverMoreThanOneComponent?, animated: $falseOrTrue). I'm not certain of the last two arguments, but if those are simple (incomponent: 0, animated: false), I can submit you a pull request that does that

**Comment by ortuman** [comment]
You caught it! ;)

Thanks for reporting the bug. Just fixed and pushed last changes. Hope it helps!!!

**Comment by mgerlach-klick** [comment]
Awesome! Thank you a lot and thank you for your neat library in general!
