### ISSUE TITLE
How to attach action to button?

### ISSUE THREAD

**Issue by mgerlach-klick** [ortuman/SwiftForms#29]
Hi,
I haven't found a way to attach any action to a tap of a FormButtonCell (and the example adds a button but doesn't react to it being tapped).
Shouldn't there be an option to attach a closure or a selector to it somewhere?
Thank you!

**Comment by angeloashmore** [comment]
I know this is already closed, but here's the answer taken from the example application.

```
row = FormRowDescriptor(tag: Static.button, rowType: .Button, title: "Dismiss")
row.configuration[FormRowDescriptor.Configuration.DidSelectClosure] = {
    self.view.endEditing(true)
} as DidSelectClosure
```
