### ISSUE TITLE
How to use programmatically with custom init?

### ISSUE THREAD

**Issue by ransomweaver** [ortuman/SwiftForms#30]
I need to pass a value on init, and instantiate the FormViewController subclass in code. 

I have this in my subclass: 

init(UUID: String)
    {
        super.init(nibName: nil, bundle: nil);
        self.UUID = UUID
        self.loadForm()
    }

    required init(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }

It calls the custom init, but I get this error:

assertion failed: self.form property MUST be assigned!: file /Users/ransom/jobs/sendcontact/sendcontact-ios/SwiftForms/SwiftForms/Source/controllers/FormViewController.swift, line 62

Is use of a storyboard required? Is there some other super.init i can call?

If I call super.init(syle: .Grouped) I get this error:

fatal error: use of unimplemented initializer 'init(nibName:bundle:)' for class 'SendContact.CardFormController'

**Comment by confile** [comment]
+1

**Comment by confile** [comment]
@ortuman do you have any solution for that?

**Comment by ransomweaver** [comment]
I ended up using a storyboard, and this:

required init(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        self.loadForm()
    }

 then in loadForm() get the value from a singleton :/

**Comment by confile** [comment]
@ransomweaver  how do you load the view from storyboard?

**Comment by ransomweaver** [comment]
@confile the usual way, put a UIViewController on the storyboard, set its class to your custom class, then segue to it or instantiate the UIStoryboard in code and initiate the controller using the storyboard identifier for the controller.

**Comment by confile** [comment]
ok thank you!
