### ISSUE TITLE
How to preload fields from database?

### ISSUE THREAD

**Issue by Vivanda** [ortuman/SwiftForms#37]
Instead of using the placeholder fields I would like to pre-fill the fields directly from the database. How would I do that? Thanks for the help.

**Comment by bevbomb** [comment]
If you mean by filling out values/placeholders from a external source before loading the form, this isn't that hard to do, but will require you to have the full amount of data before presenting the view for which you can load them. I've done this using a series of questions from a database loaded in and i loop through them, using JSON key names as the field tags
