### ISSUE TITLE
TextField for .Text returning nil when having spaces

### ISSUE THREAD

**Issue by bevbomb** [ortuman/SwiftForms#41]
So the formValues() returns a field nil if its a .Text and has spaces, plus the spaces aren't applied when you add one, instead they are applied once you start typing characters after

**Comment by vrwim** [comment]
This is expected behaviour, as it trims off all `whitespaceAndNewline` Characters. The row sets its own value to `nil` if `count(value) == 0`.

This is the relevant code:

        textField.addTarget(self, action: "editingChanged:", forControlEvents: .EditingChanged)
    func editingChanged(sender: UITextField) {
        let trimmedText = sender.text.stringByTrimmingCharactersInSet(NSCharacterSet.whitespaceAndNewlineCharacterSet())
        rowDescriptor.value = count(trimmedText) > 0 ? trimmedText : nil
    }

Not an issue.
