### ISSUE TITLE
Open modal UIViewController

### ISSUE THREAD

**Issue by steffimueller** [ortuman/SwiftForms#43]
[XLForm](https://github.com/xmartlabs/XLForm) can open modal UIViewController by clicking on a line in the form which has an arrow to the right.

Is it possible to do something like this with SwiftForms?

**Comment by angeloashmore** [comment]
To style the cell with the DisclosureIndicator (the right-facing arrow), add this to `row.configuration[FormRowDescriptor.Configuration.CellConfiguration]`:

```swift
["accessoryType": UITableViewCellAccessoryType.DisclosureIndicator.rawValue]
```

**Comment by angeloashmore** [comment]
To have a modal view appear, set a closure to instantiate a view controller. See https://github.com/ortuman/SwiftForms/issues/29.
