### ISSUE TITLE
Dynamic array of choices for .Picker

### ISSUE THREAD

**Issue by triedal** [ortuman/SwiftForms#48]
From the example in the docs you have to have a predetermined array of choices for the switch statement. Is it possible to have a dynamic array using a for loop or something?

**Comment by ortuman** [comment]
Sure, try changing FormRowDescriptor.Configuration.Options value and reloading the table. This should do the job!

**Comment by vineethvijayan** [comment]
@triedal Did it work, I am a newbie to swift and I cannot figure it out, if you have a working answer can you please post the code? Much appreciated
