### ISSUE TITLE
Inline Select (date, etc)

### ISSUE THREAD

**Issue by mbopp** [ortuman/SwiftForms#51]
Are there any plans or suggestions for adding selectors like date and time inline (calendar app, etc), rather than sliding up from the bottom?  I realize sliding from the bottom is the default functionality in iOS, and sliding down subsequent rows and displaying the selector directly beneath the field is not simple functionality to add. I've gone through the pain of doing this in the past.  What are your thoughts on this functionality being part of this library?

Thanks for the great project.

**Comment by ortuman** [comment]
Yeah! I'm planing to implement in future versions. I'll make you know as soon as it's available.

Thanks for your contribution!
