### ISSUE TITLE
2 picker view, Country and State Multi level picker view

### ISSUE THREAD

**Issue by vineethvijayan** [ortuman/SwiftForms#56]
Is there a way to add Country and State picker view

The state list should change based on Country.

Is there any way to do it? Please help

**Comment by HughJia** [comment]
same problem bothers me...

**Comment by Deub27** [comment]
Same problem. Did you manage to solve the issue ?

**Comment by ortuman** [comment]
For that particular case you should create your own custom cell. Default cell types should be more generalistic.

**Comment by RainbowMango** [comment]
I extend SwiftForms to support two picker view and used in [my project ](https://github.com/RainbowMango/DecorationBus). But unfortunately, pull request has been rejected by ortuman:(.
