### ISSUE TITLE
Can I add custom cell?

### ISSUE THREAD

**Issue by y25zhao** [ortuman/SwiftForms#71]
Not sure if this is doable. What if I want to add my own cell in the form?

**Comment by malayli** [comment]
I tried this but it doesn't work:

var row: FormRowDescriptor! = FormRowDescriptor()
row.configuration[FormRowDescriptor.Configuration.CellClass] = UserCell.self
section1.addRow(row)

It seems also that it doesn't load the cell from xib file.
