### ISSUE TITLE
Ability to Adjust Separator Insets?

### ISSUE THREAD

**Issue by jtkendall** [ortuman/SwiftForms#78]
Is there a way to adjust cell separator insets? I've tried just passing "separatorInsets" and "layoutMargins" to the cell configuration but it's not affecting them at all.

```
row.configuration[FormRowDescriptor.Configuration.CellConfiguration] = ["layoutMargins" : UIEdgeInsetsZero, "separatorInsets" : UIEdgeInsetsZero]
```

**Comment by PeterGumball** [comment]
Hello @jtkendall,

Issue is closed without any comment, is this now possible?

For empty cells this works fine (see Screenshot):
```
tableView.layoutMargins = UIEdgeInsetsZero
tableView.separatorInset = UIEdgeInsetsZero
```

For filled cells this doesn't works (see Screenshot):
```
override func tableView(tableView: UITableView, willDisplayCell cell: UITableViewCell, forRowAtIndexPath indexPath: NSIndexPath) {
    cell.separatorInset = UIEdgeInsetsZero
    cell.layoutMargins = UIEdgeInsetsZero
}

```
![bildschirmfoto 2016-07-25 um 15 19 31](https://cloud.githubusercontent.com/assets/324176/17102759/5ea70f12-527b-11e6-9fb2-24a0268e77df.png)

Thanks for your help and your library.
