### ISSUE TITLE
Problem when value set on rowType: .MultipleSelector, value can't be unset

### ISSUE THREAD

**Issue by daisylassie** [ortuman/SwiftForms#79]
if you set a value for a .MultipleSelector and want to uncheck this value, this isn't possible. the checkmark remains every.

**Comment by daisylassie** [comment]
this happens only when

AllowsMultipleSelection = true

**Comment by FrancisBaileyH** [comment]
@daisylassie I'm also getting this bug too, have you found a solution at all?
