### ISSUE TITLE
Not possible to pre-populate values

### ISSUE THREAD

**Issue by xcodewarrier** [ortuman/SwiftForms#80]
Given the following code:

        let form = FormDescriptor()
        let section1 = FormSectionDescriptor()
        var row: FormRowDescriptor!
        
        row = FormRowDescriptor(tag: type, rowType: .MultipleSelector, title: title)
        row.configuration[FormRowDescriptor.Configuration.Options] = content
        row.configuration[FormRowDescriptor.Configuration.AllowsMultipleSelection] = true
        row.configuration[FormRowDescriptor.Configuration.TitleFormatterClosure] = { value in
            
            for(var i=0;i<content.count;i++){
                if(value == content[i]){
                    return "\(value)"
                }
            }
            return "-1"
            
            } as TitleFormatterClosure

        section1.addRow(row)

it doesn't seem to be possible to pre-populate the form with selected values.

This is important in the case of a filter view controller, where the user may dismiss the filter modal and then re-open at a later date.

**Comment by FrancisBaileyH** [comment]
@xcodewarrier you can just do 

    row.value = [ "some", "values" ]

So long as the row is a type that has multiple values
