### ISSUE TITLE
No spacing between 2 sections

### ISSUE THREAD

**Issue by vhs123** [ortuman/SwiftForms#82]
I have added many sections in the form, but there is no spacing between them:
![screen shot 2015-12-12 at 7 07 20 pm](https://cloud.githubusercontent.com/assets/13916381/11762143/f5fcee38-a103-11e5-965a-a56e88fc88f6.png)

Here is a part of the code:

	...
	
	let section4 = FormSectionDescriptor()
	row = FormRowDescriptor(tag: Static.phoneOfficeTag, rowType: .Phone, title: GlobalConstants.PHONE_OFFICE as String)
	config = configGlobal
	if let val = mUser.PhoneOffice as? String where val.isEmpty==false
	{   config["textField.text"] = val }
	row.configuration[FormRowDescriptor.Configuration.CellConfiguration] = config
	section4.addRow(row)
	    
	    
	let section5 = FormSectionDescriptor()
	row = FormRowDescriptor(tag: Static.emailTag, rowType: .Email, title: "Email")
	config = configGlobal
	if let val = mUser.Email as? String where val.isEmpty==false
	{   config["textField.text"] = val }
	row.configuration[FormRowDescriptor.Configuration.CellConfiguration] = config
	section5.addRow(row)
	
	...

**Comment by nahouto** [comment]
Hello vhs123, I just would like to contact you. Can you please tell me if your issue about Linkedin oAuth2 there (https://github.com/p2/OAuth2/issues/43#issuecomment-166116459) is resolved and how ? Thanks.

**Comment by vhs123** [comment]
Hi Nahouto,

Sorry for replying late. I could not resolve the issue. I am currently
using another library: https://github.com/OAuthSwift/OAuthSwift

On Sun, Dec 20, 2015 at 7:42 PM, nahouto <notifications@github.com> wrote:

> Hello vhs123, I just would like to contact you. Can you please tell me if
> your issue about Linkedin oAuth2 there (p2/OAuth2#43 (comment)
> <https://github.com/p2/OAuth2/issues/43#issuecomment-166116459>) is
> resolved and how ? Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ortuman/SwiftForms/issues/82#issuecomment-166119851>.
>



-- 
Regards,
Vishalaksh
