### ISSUE TITLE
Carthage issue framework schemes dependency problem.

### ISSUE THREAD

**Issue by eddwinpaz** [ortuman/SwiftForms#86]
When using the command ---> carthage update --platform iOS

    *** Building scheme "OAuthSwift" in OAuthSwift.xcworkspace
    *** Skipped building SwiftForms due to the error:
    Dependency "SwiftForms" has no shared framework schemes for any of the platforms: iOS

**Comment by MattesGroeger** [comment]
+1

Yep, just ran into the same issue.

```
If you believe this to be an error, please file an issue with the maintainers at https://github.com/ortuman/SwiftForms/issues/new
```
