### ISSUE TITLE
Row values

### ISSUE THREAD

**Issue by arunnetram** [ortuman/SwiftForms#89]
The row values are not getting picked up when we submit the form. This is happening even on the example project that comes with this library.

**Comment by jincon** [comment]
Yes，I also find it

**Comment by MHX792** [comment]
I can confirm this.
Any fix for this soon?

**Comment by ortuman** [comment]
Working on fixing it... thanks for info. I hope to have it fixed today along with other issues. :)

**Comment by ortuman** [comment]
Fixed issue. Sorry for the inconvenience. :)
